# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    output_directory = 'test_output'
    FileUtils.rm_rf(output_directory)
    scan(
      output_types: '',
      output_directory: output_directory,
      result_bundle: true,
      fail_build: false
    )
    UI.message '✅  scan succeeded'
    trainer(
      path: output_directory,
      output_directory: output_directory,
      fail_build: false
    )
    UI.message '✅  trainer succeeded'
    puts `cat test_output/report.junit`
  end
end
