# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    FileUtils.rm_rf('test_output')
    begin
      scan(
        devices: ['iPhone 13', 'iPhone 13 Pro Max'],
        output_types: 'junit',
        fail_build: false
      )
      UI.message '✅  scan succeeded'
      puts `cat test_output/report.junit`
    rescue StandardError => e
      UI.error "❌ scan failed, exception backtrace: #{e.backtrace}"
    end
  end
end
